#!/bin/sh

set -e

if [ ! -f /usr/local/bin/brew ]; then
  /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
fi

if [ ! -d ~/dotfiles ]; then
  cd ~
  git clone git@github.com:ychino/dotfiles.git
fi

brew bundle -v --file=~/dotfiles/Brewfile

stow -v -d ~/dotfiles/packages -t ~ zsh
